patreon: SigureMo
custom:
  [
    "https://afdian.net/@siguremo",
    "https://raw.githubusercontent.com/SigureMo/image-hosting/master/sponsor/alipay.png",
    "https://raw.githubusercontent.com/SigureMo/image-hosting/master/sponsor/wechat.png",
  ]
