name: "✨ New feature proposal"
description: Propose a new feature to be added to bilili
title: "✨ "
labels: ["enhancement: pending triage"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 特性描述
      description: 详述你所需要的特性～
      placeholder: "(๑>؂<๑）"
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: 建议解决方案
      description: 你所建议的解决方案～
      placeholder: "ː̗̀(o›ᴗ‹o)ː̖́"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 额外信息
      description:
      placeholder: "ヾ(❀^ω^)ﾉﾞ"
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一点点的自我检查
      description: 在你提交 issue 之前，麻烦确认自己是否已经完成了以下检查：
      options:
        - label: 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
          required: true
        - label: 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题
          required: true
