name: VuePress Deploy

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: deploy-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          lfs: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: "docs/package.json"
          version: "latest"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "docs/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./docs
        run: pnpm i --frozen-lockfile

      - name: Build VuePress site
        working-directory: ./docs
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vuepress/dist
          external_repository: SigureMo/docs # 编译后直接转发到个人账户的 vercel-docs
          publish_branch: bilili
          force_orphan: true
          commit_message: ":rocket: deploy: "
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
