name: VuePress Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: deploy-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        working-directory: ./docs
        run: pnpm i --frozen-lockfile

      - name: Build VuePress site
        working-directory: ./docs
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vuepress/dist
          external_repository: SigureMo/docs # 编译后直接转发到个人账户的 vercel-docs
          publish_branch: bilili
          force_orphan: true
          commit_message: ":rocket: deploy: "
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
